name: Build Python Action

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Python version to build"
      architecture:
        required: false
        type: string
        default: "x86-64"
        description: "Architecture to build for"
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      architecture:
        required: false
        type: string
        default: "x86-64"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      sub_version: ${{ needs.sub_version.outputs.sub_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # - name: Determine LLVM version
      #   run: |
      #     LLVM_VERSION=$(python3 - <<'PY'
      #       from packaging.version import Version
            
      #       v = Version("${{ inputs.version }}")
            
      #       if v >= Version("3.15"):
      #           print(21)
      #       elif v >= Version("3.14"):
      #           print(19)
      #       elif v >= Version("3.13"):
      #           print(18)
      #       else:
      #           print(22)
      #       PY
      #       )
      #     echo "LLVM_VERSION=$LLVM_VERSION" >> $GITHUB_ENV

      # - name: Install LLVM 21
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x llvm.sh
      #     sudo ./llvm.sh $LLVM_VERSION

      #     echo "LLVM_VERSION=$LLVM_VERSION" >> $GITHUB_ENV
      #     echo "CC=clang-$LLVM_VERSION" >> $GITHUB_ENV
      #     echo "CXX=clang++-$LLVM_VERSION" >> $GITHUB_ENV
      #     echo "AR=llvm-ar-$LLVM_VERSION" >> $GITHUB_ENV
      #     echo "RANLIB=llvm-ranlib-$LLVM_VERSION" >> $GITHUB_ENV

      #     sudo ln -s /usr/bin/llvm-ar-$LLVM_VERSION /usr/bin/llvm-ar
      #     sudo ln -s /usr/bin/llvm-ranlib-$LLVM_VERSION /usr/bin/llvm-ranlib
      #     sudo ln -s /usr/bin/llvm-profdata-$LLVM_VERSION /usr/bin/llvm-profdata

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: get sub_version
        id: sub_version
        run: echo "sub_version=$(python3 get_latest.py ${{ inputs.version }})" >> "$GITHUB_ENV"

      - name: Install compile dependencies
        run: |
          python3 install_dependencies.py $sub_version

      - name: Download and compile Python
        run: |
          wget https://www.python.org/ftp/python/${{ inputs.version }}/Python-$sub_version.tgz
          tar xzf Python-$sub_version.tgz
          cd Python-$sub_version
          
          CFLAGS="${{ env.PYTHON_CFLAGS }}" \
          ./configure $(python3 ../get_opts.py ${{ inputs.version }})
          
          make -j4 CFLAGS="${{ env.PYTHON_CFLAGS }}"
        env:
          PYTHON_CFLAGS: -march=${{ inputs.architecture }} -O3

      - name: Install and package Python
        run: |
          cd Python-$sub_version
          if [[ $sub_version == *.*.* ]]; then
            echo "major_minor_version=${sub_version%.*}" >> "$GITHUB_ENV"
            major_minor_version=${sub_version%.*}
          else
            echo "major_minor_version=$sub_version" >> "$GITHUB_ENV"
            major_minor_version=$sub_version
          fi
          sudo checkinstall -D --pkgname=python$major_minor_version --pkgversion=$sub_version --pkgrelease=1 --arch=amd64 --default make altinstall

      - name: Upload Python package
        uses: actions/upload-artifact@v4
        with:
          name: python${{ env.sub_version }}-${{ inputs.architecture }}
          path: Python-${{ env.sub_version }}/python${{ env.major_minor_version }}_${{ env.sub_version }}-1_amd64.deb
