name: Build Python Action

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      architecture:
        required: false
        type: string
        default: "amd64"
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      architecture:
        required: false
        type: string
        default: "amd64"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libbz2-dev libsqlite3-dev libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev wget checkinstall

    - name: Download and compile Python
      run: |
        wget https://www.python.org/ftp/python/${{ inputs.version }}/Python-${{ inputs.version }}.tgz
        tar xzf Python-${{ inputs.version }}.tgz
        cd Python-${{ inputs.version }}
        ./configure ${{ env.PYTHON_CONFIGURE_OPTS }}
        make -j4 CFLAGS="${{ env.PYTHON_CFLAGS }}"
      env:
        PYTHON_CONFIGURE_OPTS: --enable-optimizations --with-lto
        PYTHON_CFLAGS: -march={{ inputs.architecture }} -mtune={{ inputs.architecture }} -O3

    - name: Install and package Python
      run: |
        cd Python-${{ inputs.version }}
        sudo checkinstall -D --pkgname=python-${{ inputs.version }}-{{ inputs.architecture }} --default make altinstall

    - name: Upload Python package
      uses: actions/upload-artifact@v4
      with:
        name: python${{ inputs.version }}-{{ inputs.architecture }}
        path: Python-${{ inputs.version }}/python-${{ inputs.version }}-{{ inputs.architecture }}.deb
