name: Daily Python Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate version list
        id: set-matrix
        run: echo "matrix=$(python generate_versions.py)" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ${{ fromJSON(needs.prepare.outputs.matrix) }}
        architecture: ["x86-64", "alderlake", "znver3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Python
        uses: ./.github/workflows/build.yml
        with:
          version: ${{ matrix.version }}
          architecture: ${{ matrix.architecture }}
